## Server Properties
server:
  port: 9000
  compression.enabled: true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#spring.datasource.url= jdbc:mysql://ec2-3-36-128-65.ap-northeast-2.compute.amazonaws.com:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#spring.datasource.url= jdbc:mysql://localhost:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3307/reading_ocean
  username: root
  password: clbeeroot
  initialization-mode: always

## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa:
  properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  hibernate.ddl-auto: update

## Hibernate Logging
logging.level.org.hibernate.SQL: DEBUG

## Jackson Properties
spring.jackson:
  serialization.WRITE_DATES_AS_TIMESTAMPS: false
  time-zone: UTC

## App Properties
app.jwtSecret: JWTSuperSecretKey
app.jwtExpirationInMs: 604800000

## Spring Profiles
spring.profiles.active: prod

## books
datafile:
  books: books.csv

## users
users:
  admin: clbee,readingocean
  subscriber: 청산학원,한강중학교