INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PUBLISHER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_SUBSCRIBER');
